a = int (input ('Ingrese un numero:'))
b = int (input ('Ingrese otro numero: '))
print(f'La suma de {a} y {b} es {a+b}')
print(f'La resta de {a} y {b} es {a-b}')
print(f'La multiplicación de {a} y {b} es {a*b}')
print(f'El cociente entero de {a} y {b} es {a//b}')
print(f'El cociente decimal de {a} y {b} es {a/b}')
print(f'El residuo de {a} y {b} es {a%b}')
print(f'¿Es {a} mayor que {b}? {a>b}')
print(f'¿Es {a} menor que {b}? {a<b}')
print(f'{a} elevado a la {b} es {a**b}')